[tool]
id = "com.thelightphone.radio"
label = "Radio"
versionCode = 5
versionName = "1.1.2"
permissions = [
    "android.permission.INTERNET",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.WAKE_LOCK",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK"
]
serverPackage = "com.thelightphone.sdk.emulator"
sharedUserId = "com.thelightphone.sdk"
orientation = "portrait"
enableBackgroundAudio = true
